/*
Problem: Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then adding one more letter at a random position.

Return the letter that was added to t.

Constraints:

- 0 <= s.length <= 1000
- t.length == s.length + 1
- s and t consist of lowercase English letters.
*/


// Function to find the additional character in string t compared to string s
const findTheDifference = (s, t) => {
    // Initialize sum of character codes for string s
    let charCodeSumS = 0;
    // Initialize sum of character codes for string t
    let charCodeSumT = 0;

    // Calculate the sum of character codes for string s
    for (let char of s) {
        charCodeSumS += char.charCodeAt(0);
    }

    // Calculate the sum of character codes for string t
    for (let char of t) {
        charCodeSumT += char.charCodeAt(0);
    }

    // Return the character that was added to string t
    return String.fromCharCode(charCodeSumT - charCodeSumS);
};
